from typing import List, Dict, Any

EMAILS: List[Dict[str, Any]] = [
    # ── URGENT ──────────────────────────────────────────────────────────────
    {"id":"e001","subject":"URGENT: Server Down - Production Impact","body":"Our main production server has been down for 30 minutes. Revenue impact is $10k/min. Need immediate escalation.","sender":"ops-team@company.com","timestamp":"2024-01-15T09:00:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["apologize","escalat","immediately","priorit"],"min_response_length":80,"must_resolve":True}},
    {"id":"e002","subject":"Data breach detected - customer records exposed","body":"Our security system flagged a potential data breach. Approximately 10,000 customer records may have been exposed. We need immediate action from the security team.","sender":"security@company.com","timestamp":"2024-01-15T09:05:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["apologize","security","immediately","team"],"min_response_length":100,"must_resolve":True}},
    {"id":"e003","subject":"CEO email - System outage affecting board presentation","body":"This is the CEO. Our entire presentation system is down and I have a board meeting in 20 minutes. Fix this NOW.","sender":"ceo@company.com","timestamp":"2024-01-15T09:10:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["apologize","immediately","priorit","resolv"],"min_response_length":80,"must_resolve":True}},
    {"id":"e004","subject":"Payment gateway down - no transactions processing","body":"Since 8 AM our payment gateway has been returning errors. We cannot process any customer payments. This is losing us thousands of dollars per hour.","sender":"finance@client.com","timestamp":"2024-01-15T09:15:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["apologize","payment","fix","team"],"min_response_length":80,"must_resolve":True}},
    {"id":"e005","subject":"Password reset not working - locked out before presentation","body":"I've been locked out of my account for 2 hours. The password reset email never arrives. I have an important presentation in 1 hour and need access NOW.","sender":"sarah.smith@client.org","timestamp":"2024-01-15T09:20:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["apologize","reset","access","manual"],"min_response_length":80,"must_resolve":True}},
    {"id":"e006","subject":"Legal threat - customer threatening lawsuit","body":"I am writing to inform you that if my refund of $4,500 is not processed within 24 hours, I will be filing a lawsuit against your company. This is my final notice.","sender":"angry.customer@gmail.com","timestamp":"2024-01-15T09:25:00Z","ground_truth":{"category":"urgent","department":"billing","priority":5,"keywords_required":["apologize","refund","contact","review"],"min_response_length":100,"must_resolve":True}},
    {"id":"e007","subject":"Hospital system integration failure - patient data at risk","body":"Our hospital integration with your API has failed completely. Patient scheduling and medical record access is down. This is a life-safety issue. We need engineers immediately.","sender":"it@cityhospital.org","timestamp":"2024-01-15T09:30:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["apologize","escalat","immediately","engineer"],"min_response_length":100,"must_resolve":True}},
    {"id":"e008","subject":"Invoice #4521 - Unauthorized charges - threatening chargeback","body":"I have been trying to resolve my invoice dispute for 3 weeks. Invoice #4521 shows $2,300 in charges I did not authorize. If not resolved today I am calling my bank.","sender":"john.doe@client.com","timestamp":"2024-01-15T09:35:00Z","ground_truth":{"category":"urgent","department":"billing","priority":4,"keywords_required":["apologize","invoice","review","contact"],"min_response_length":80,"must_resolve":True}},
    {"id":"e009","subject":"API returning 500 errors after your update v2.3.1","body":"Since your latest update (v2.3.1), our API integration has been returning 500 errors on every POST request. This is blocking our entire dev team of 20 engineers.","sender":"dev@partner-company.com","timestamp":"2024-01-15T09:40:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["apologize","bug","fix","version"],"min_response_length":100,"must_resolve":True}},
    {"id":"e010","subject":"Employee terminated - access must be revoked immediately","body":"We have terminated employee John Smith (ID: JS-4521) effective immediately due to misconduct. Please revoke all system access, email accounts, and VPN credentials right now.","sender":"hr-director@company.com","timestamp":"2024-01-15T09:45:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["access","immediately","revok","confirm"],"min_response_length":60,"must_resolve":True}},

    # ── NORMAL ───────────────────────────────────────────────────────────────
    {"id":"e011","subject":"Team lunch next Friday?","body":"Hey everyone, thinking of organizing a team lunch next Friday at noon. Let me know if you're interested and any dietary preferences!","sender":"alice@company.com","timestamp":"2024-01-15T10:00:00Z","ground_truth":{"category":"normal","department":"hr","priority":1,"keywords_required":[],"min_response_length":20,"must_resolve":False}},
    {"id":"e012","subject":"Request for enterprise pricing","body":"Hi, we are a 500-person company looking to switch to your platform. Could you share enterprise pricing and schedule a demo for next week?","sender":"procurement@bigcorp.com","timestamp":"2024-01-15T10:05:00Z","ground_truth":{"category":"normal","department":"sales","priority":4,"keywords_required":["pricing","demo","enterprise","team"],"min_response_length":80,"must_resolve":False}},
    {"id":"e013","subject":"Feedback on your product - overall positive","body":"Hi, I've been using your product for 3 months now and overall I'm quite happy. A few minor suggestions: the export feature could be faster and the UI could use some improvements.","sender":"customer123@email.com","timestamp":"2024-01-15T10:10:00Z","ground_truth":{"category":"normal","department":"support","priority":2,"keywords_required":["thank","feedback","team"],"min_response_length":50,"must_resolve":False}},
    {"id":"e014","subject":"Question about GDPR compliance features","body":"We are evaluating your platform for use in the EU. Could you provide documentation on your GDPR compliance features, data residency options, and DPA agreement process?","sender":"legal@eucompany.de","timestamp":"2024-01-15T10:15:00Z","ground_truth":{"category":"normal","department":"sales","priority":3,"keywords_required":["gdpr","compliance","document","team"],"min_response_length":80,"must_resolve":False}},
    {"id":"e015","subject":"Monthly newsletter subscription confirmation","body":"Please confirm my subscription to your monthly product newsletter. I'm interested in updates about new features and industry insights.","sender":"subscriber@email.com","timestamp":"2024-01-15T10:20:00Z","ground_truth":{"category":"normal","department":"support","priority":1,"keywords_required":["confirm","subscri"],"min_response_length":30,"must_resolve":False}},
    {"id":"e016","subject":"Partnership opportunity - joint webinar proposal","body":"Hi, I represent TechLeaders community of 50,000 developers. We'd love to co-host a webinar with your team about AI best practices. Would you be open to a quick call?","sender":"partnerships@techleaders.io","timestamp":"2024-01-15T10:25:00Z","ground_truth":{"category":"normal","department":"sales","priority":3,"keywords_required":["partner","webinar","call","team"],"min_response_length":60,"must_resolve":False}},
    {"id":"e017","subject":"Can I change my subscription plan?","body":"I'm currently on the Basic plan and would like to upgrade to Pro. Can you walk me through the process and let me know if there are any prorated charges?","sender":"user456@gmail.com","timestamp":"2024-01-15T10:30:00Z","ground_truth":{"category":"normal","department":"billing","priority":2,"keywords_required":["upgrade","plan","billing","prorat"],"min_response_length":60,"must_resolve":False}},
    {"id":"e018","subject":"How to export data to CSV?","body":"I've been trying to find the CSV export feature but can't locate it in the dashboard. Is this available on my current plan? If so, where can I find it?","sender":"helpme@startup.com","timestamp":"2024-01-15T10:35:00Z","ground_truth":{"category":"normal","department":"support","priority":2,"keywords_required":["export","csv","dashboard","plan"],"min_response_length":50,"must_resolve":False}},
    {"id":"e019","subject":"Job application - Senior Software Engineer position","body":"Dear Hiring Team, I am writing to apply for the Senior Software Engineer position posted on LinkedIn. I have 8 years of experience in Python and distributed systems. Please find my resume attached.","sender":"jobseeker@email.com","timestamp":"2024-01-15T10:40:00Z","ground_truth":{"category":"normal","department":"hr","priority":2,"keywords_required":["application","resume","team","review"],"min_response_length":50,"must_resolve":False}},
    {"id":"e020","subject":"Request for product demo - 200 seat license evaluation","body":"Our procurement team is evaluating solutions for our 200-person engineering department. We would like a personalized demo focusing on team collaboration and API features.","sender":"cto@enterprise.com","timestamp":"2024-01-15T10:45:00Z","ground_truth":{"category":"normal","department":"sales","priority":4,"keywords_required":["demo","schedule","team","engineer"],"min_response_length":80,"must_resolve":False}},

    # ── SPAM ─────────────────────────────────────────────────────────────────
    {"id":"e021","subject":"50% OFF - Limited Time Offer Just For You!","body":"Click here to claim your exclusive discount! This offer expires in 24 hours. Don't miss out on amazing deals at unbelievable prices!","sender":"noreply@deals-promo.net","timestamp":"2024-01-15T11:00:00Z","ground_truth":{"category":"spam","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e022","subject":"Congratulations! You've won a free iPhone 15 Pro!","body":"You have been selected as our lucky winner! Claim your free iPhone 15 Pro by clicking the link and entering your credit card details for shipping costs only.","sender":"winner@free-prizes-online.xyz","timestamp":"2024-01-15T11:05:00Z","ground_truth":{"category":"spam","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e023","subject":"Nigerian Prince needs your help - $45 million transfer","body":"Dear Friend, I am a Nigerian Prince with $45 million to transfer. I need your bank account details to complete the transfer and will share 40% with you as reward.","sender":"prince@nigeria-royal.tk","timestamp":"2024-01-15T11:10:00Z","ground_truth":{"category":"spam","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e024","subject":"Your account has been compromised - verify now!!","body":"URGENT: We detected suspicious activity on your account. Click here immediately to verify your identity and prevent account suspension. Enter your password to confirm.","sender":"security-alert@accountverify-now.com","timestamp":"2024-01-15T11:15:00Z","ground_truth":{"category":"spam","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e025","subject":"Make $5000 per day working from home!!!","body":"Discover the secret method that lets ordinary people earn $5000 per day from home! No experience needed. Limited spots available. Click now before it's too late!!!","sender":"rich@work-from-home-secrets.biz","timestamp":"2024-01-15T11:20:00Z","ground_truth":{"category":"spam","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e026","subject":"Your parcel could not be delivered - pay fee now","body":"We attempted to deliver your parcel but were unsuccessful. Please pay a $2.99 redelivery fee by clicking the link below within 24 hours or your package will be returned.","sender":"delivery@parcel-redelivery-fee.com","timestamp":"2024-01-15T11:25:00Z","ground_truth":{"category":"spam","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e027","subject":"Cheap Rx medications - no prescription needed","body":"Buy prescription medications at 90% discount. No doctor visit required. Shipped discreetly to your door. Visit our online pharmacy today for unbeatable prices.","sender":"pharma@cheap-meds-online.ru","timestamp":"2024-01-15T11:30:00Z","ground_truth":{"category":"spam","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e028","subject":"IRS Notice: Unpaid taxes - arrest warrant issued","body":"This is the IRS. You have unpaid taxes of $3,450. An arrest warrant has been issued in your name. Call us immediately at 1-800-FAKE-IRS to avoid arrest.","sender":"irs-notice@tax-collection-dept.net","timestamp":"2024-01-15T11:35:00Z","ground_truth":{"category":"spam","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},

    # ── PROMOTIONAL ──────────────────────────────────────────────────────────
    {"id":"e029","subject":"New Feature Launch: AI-powered analytics dashboard","body":"We're excited to announce our new AI-powered analytics dashboard! Get deeper insights into your data with our latest release. Upgrade to Pro to access this feature today.","sender":"product@ourcompany.com","timestamp":"2024-01-15T12:00:00Z","ground_truth":{"category":"promotional","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e030","subject":"Black Friday Sale - 40% off all annual plans","body":"Our biggest sale of the year is here! Get 40% off all annual plans this Black Friday. Use code BLACKFRIDAY40 at checkout. Offer ends midnight Sunday.","sender":"marketing@ourcompany.com","timestamp":"2024-01-15T12:05:00Z","ground_truth":{"category":"promotional","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e031","subject":"Webinar invite: How to 10x your team productivity","body":"Join us this Thursday for a free webinar on boosting team productivity. Our CEO will share exclusive strategies used by Fortune 500 companies. Register now - limited seats!","sender":"events@ourcompany.com","timestamp":"2024-01-15T12:10:00Z","ground_truth":{"category":"promotional","department":"support","priority":1,"keywords_required":[],"min_response_length":0,"must_resolve":False}},
    {"id":"e032","subject":"Your free trial ends in 3 days - upgrade now","body":"Your 14-day free trial ends in 3 days. Don't lose access to your data and workflows. Upgrade to a paid plan today and get 20% off your first month with code TRIAL20.","sender":"billing@ourcompany.com","timestamp":"2024-01-15T12:15:00Z","ground_truth":{"category":"promotional","department":"support","priority":2,"keywords_required":[],"min_response_length":0,"must_resolve":False}},

    # ── MEDIUM DIFFICULTY ────────────────────────────────────────────────────
    {"id":"e033","subject":"Not happy with service - considering cancellation","body":"I've been a customer for 2 years but lately the service quality has dropped. Response times are slow and two features I rely on are broken. I'm thinking of switching to a competitor.","sender":"longtime.customer@business.com","timestamp":"2024-01-15T13:00:00Z","ground_truth":{"category":"normal","department":"support","priority":4,"keywords_required":["apologize","feedback","resolv","team"],"min_response_length":100,"must_resolve":False}},
    {"id":"e034","subject":"Double charged on my credit card this month","body":"I just noticed I was charged twice this month - $99 on the 1st and another $99 on the 3rd. Please refund the duplicate charge as soon as possible.","sender":"customer@email.com","timestamp":"2024-01-15T13:05:00Z","ground_truth":{"category":"normal","department":"billing","priority":3,"keywords_required":["apologize","refund","charg","review"],"min_response_length":60,"must_resolve":True}},
    {"id":"e035","subject":"Feature request - bulk import from CSV","body":"It would be extremely helpful if you could add bulk import functionality from CSV files. Many of us have large datasets and importing one by one is very time consuming.","sender":"poweruser@company.com","timestamp":"2024-01-15T13:10:00Z","ground_truth":{"category":"normal","department":"support","priority":2,"keywords_required":["thank","feature","team","consider"],"min_response_length":50,"must_resolve":False}},
    {"id":"e036","subject":"Staff member being harassed - need HR intervention","body":"I am reporting that a colleague has been making inappropriate comments to me and two other team members over the past month. This needs to be addressed immediately by HR.","sender":"employee.confidential@company.com","timestamp":"2024-01-15T13:15:00Z","ground_truth":{"category":"urgent","department":"hr","priority":5,"keywords_required":["apologize","confidential","hr","immediately"],"min_response_length":100,"must_resolve":True}},
    {"id":"e037","subject":"System very slow - affecting work","body":"For the past week our entire team has noticed the platform is extremely slow. Pages take 10-15 seconds to load. This is affecting our productivity significantly.","sender":"team.lead@client.com","timestamp":"2024-01-15T13:20:00Z","ground_truth":{"category":"normal","department":"technical","priority":3,"keywords_required":["apologize","investigat","performance","team"],"min_response_length":80,"must_resolve":False}},
    {"id":"e038","subject":"Refund request - product not as described","body":"I purchased the Enterprise plan based on your website which mentioned unlimited users. After purchase I found out there is a 50 user limit. This is misleading. I want a full refund.","sender":"deceived.customer@startup.com","timestamp":"2024-01-15T13:25:00Z","ground_truth":{"category":"normal","department":"billing","priority":4,"keywords_required":["apologize","refund","review","clarif"],"min_response_length":100,"must_resolve":True}},
    {"id":"e039","subject":"Competitor offering same features at half price","body":"I've received an offer from CompetitorX offering the same features as your Pro plan at $49/month vs your $99/month. Can you match this price or offer any discount to retain my business?","sender":"negotiating.customer@business.com","timestamp":"2024-01-15T13:30:00Z","ground_truth":{"category":"normal","department":"sales","priority":3,"keywords_required":["value","discount","offer","team"],"min_response_length":80,"must_resolve":False}},
    {"id":"e040","subject":"Integration with Salesforce not working","body":"We set up the Salesforce integration last week following your documentation but contact sync is not working. Contacts created in your platform don't appear in Salesforce.","sender":"salesops@company.com","timestamp":"2024-01-15T13:35:00Z","ground_truth":{"category":"normal","department":"technical","priority":3,"keywords_required":["apologize","integrat","investigat","team"],"min_response_length":80,"must_resolve":False}},

    # ── HARD DIFFICULTY ──────────────────────────────────────────────────────
    {"id":"e041","subject":"Multiple issues - billing error + account access + data loss","body":"I have three urgent issues: 1) I was charged $499 for Enterprise but only have Basic access. 2) I cannot log in to two of my sub-accounts. 3) A project I created last week has disappeared. This is completely unacceptable.","sender":"furious.enterprise.client@bigcompany.com","timestamp":"2024-01-15T14:00:00Z","ground_truth":{"category":"urgent","department":"support","priority":5,"keywords_required":["apologize","billing","access","investigat","priorit"],"min_response_length":150,"must_resolve":True}},
    {"id":"e042","subject":"GDPR data deletion request - legal requirement","body":"Under GDPR Article 17, I formally request the deletion of all my personal data from your systems. Please confirm receipt and provide a timeline for completion. Failure to comply within 30 days will be reported to the ICO.","sender":"gdpr.request@privateperson.eu","timestamp":"2024-01-15T14:05:00Z","ground_truth":{"category":"urgent","department":"support","priority":4,"keywords_required":["gdpr","delet","confirm","comply"],"min_response_length":100,"must_resolve":True}},
    {"id":"e043","subject":"Whistleblower report - financial irregularities","body":"I am an employee reporting financial irregularities I have observed. Several expense reports appear to have been falsified. I am reporting this anonymously and request this be handled with complete confidentiality.","sender":"anonymous.report@protonmail.com","timestamp":"2024-01-15T14:10:00Z","ground_truth":{"category":"urgent","department":"hr","priority":5,"keywords_required":["confidential","investigat","report","secur"],"min_response_length":100,"must_resolve":True}},
    {"id":"e044","subject":"Press inquiry - data breach story going live tomorrow","body":"I am a journalist from TechCrunch. We are publishing a story tomorrow about a data breach at your company affecting 50,000 users. I am giving you the opportunity to comment before publication. Please respond by 5 PM today.","sender":"reporter@techcrunch.com","timestamp":"2024-01-15T14:15:00Z","ground_truth":{"category":"urgent","department":"support","priority":5,"keywords_required":["confirm","comment","team","contact"],"min_response_length":100,"must_resolve":True}},
    {"id":"e045","subject":"Account takeover - someone changed my email and password","body":"Someone has taken over my account. I received an email saying my login email was changed to an address I don't recognize. I can no longer log in. I have $2,400 in credits in this account. Please help immediately.","sender":"real.owner@gmail.com","timestamp":"2024-01-15T14:20:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["apologize","secur","verify","immediately","account"],"min_response_length":100,"must_resolve":True}},
    {"id":"e046","subject":"Service level agreement breach - 99.9% uptime not met","body":"Per our Enterprise SLA, you guarantee 99.9% uptime. Your system was down for 6 hours last month which is a clear breach. We are entitled to a service credit of $15,000. Please process this within 5 business days.","sender":"legal@enterprise-client.com","timestamp":"2024-01-15T14:25:00Z","ground_truth":{"category":"urgent","department":"billing","priority":5,"keywords_required":["apologize","sla","credit","review","contact"],"min_response_length":120,"must_resolve":True}},
    {"id":"e047","subject":"Regulatory audit - need all data logs within 48 hours","body":"We are conducting a regulatory compliance audit. We require complete access logs, user activity records, and data processing records for the period January 2023 to December 2023. This is a legal requirement and must be provided within 48 hours.","sender":"audit@regulatory-body.gov","timestamp":"2024-01-15T14:30:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["comply","audit","logs","team","contact"],"min_response_length":120,"must_resolve":True}},
    {"id":"e048","subject":"Mass cancellation - entire company switching platforms","body":"Due to repeated service failures and poor support, our company (450 users, $54,000 annual contract) has decided to migrate to a competitor. Please initiate cancellation of all accounts and arrange data export within 2 weeks.","sender":"cto@large-client.com","timestamp":"2024-01-15T14:35:00Z","ground_truth":{"category":"urgent","department":"sales","priority":5,"keywords_required":["apologize","retain","export","contact","discuss"],"min_response_length":150,"must_resolve":True}},
    {"id":"e049","subject":"Child safety concern - inappropriate content on platform","body":"I am a parent and found highly inappropriate content on your platform that my 12-year-old accessed. This content should not be accessible. I am reporting this and demand immediate action and a full explanation.","sender":"concerned.parent@email.com","timestamp":"2024-01-15T14:40:00Z","ground_truth":{"category":"urgent","department":"support","priority":5,"keywords_required":["apologize","safety","investigat","immediately","action"],"min_response_length":120,"must_resolve":True}},
    {"id":"e050","subject":"Ransomware attack - systems encrypted via your integration","body":"We have suffered a ransomware attack. Our forensics team has traced the initial access point to your API integration. All our systems are now encrypted. We need your security team on a call immediately and all logs from the past 30 days.","sender":"ciso@victim-company.com","timestamp":"2024-01-15T14:45:00Z","ground_truth":{"category":"urgent","department":"technical","priority":5,"keywords_required":["apologize","secur","logs","immediately","team"],"min_response_length":150,"must_resolve":True}},
]

TASK_EMAIL_MAP = {
    "classify":  ["e021","e022","e029","e001","e011","e030","e002","e023"],
    "triage":    ["e033","e034","e037","e038","e040","e009","e008","e036"],
    "respond":   ["e041","e042","e045","e046","e048","e049","e050","e006"],
    "summarize": ["e001","e004","e006","e009","e033","e036","e041","e048"],
}

def get_emails_for_task(task: str):
    ids = TASK_EMAIL_MAP.get(task, [])
    email_map = {e["id"]: e for e in EMAILS}
    return [email_map[i] for i in ids if i in email_map]
